version: '3.5'
services:
  web:
    build: .
    networks:
      - bravo
    ports:
     - "8080:80"
    volumes:
     - ~/data:/data
  mongo:
    image: "mongo:4.0.17"
    volumes:
     - ~/data/mongo/db:/data/db
    networks:
      - bravo
networks:
  bravo:
    name: bravoWebApp
